export const allBingoItems = [
  "Speedboat",
  "Kayak",
  "Fishing rod",
  "Life jacket",
  "Sunscreen bottle",
  "Beach towel",
  "Cooler",
  "Sunglasses",
  "Picnic basket",
  "Inflatable float",
  "Paddleboard",
  "Jet ski",
  "Wakeboard",
  "Water skis",
  "Tubing behind a boat",
  "Campfire",
  "Tent",
  "RV or camper",
  "Fishing lure",
  "Tackle box",
  "Fish jumping",
  "Catfish",
  "Bass",
  "Walleye",
  "Crappie",
  "Bluegill",
  "Trout",
  "Bald eagle",
  "Osprey",
  "Great blue heron",
  "Duck",
  "Goose",
  "Pelican",
  "Seagull",
  "Coyote",
  "Deer",
  "Raccoon",
  "Squirrel",
  "Butterfly",
  "Dragonfly",
  "Firefly at dusk",
  "Cactus",
  "Yucca plant",
  "Cottonwood tree",
  "Juniper tree",
  "Piñon pine",
  "Cliff diving",
  "Rock climbing",
  "Hiking trail",
  "Binoculars",
  "Camera",
  "Sunset over the lake",
  "Starry night sky",
  "Full moon reflection on water",
  "Lighthouse",
  "Marina",
  "Boat dock",
  "Buoy",
  "No wake zone sign",
  "Lake depth marker",
  "Fish cleaning station",
  "Bait shop",
  "Souvenir shop",
  "Ice cream stand",
  "Lakeside restaurant",
  "Picnic area",
  "Playground",
  "Volleyball net",
  "Horseshoe pit",
  "Frisbee",
  "Beach ball",
  "Sand castle",
  "Floating dock",
  "Diving board",
  "Water slide",
  "Jet ski rental",
  "Boat rental",
  "Fishing guide",
  "Tour boat",
  "Parasailing",
  "Wind surfing",
  "Kite flying",
  "Hammock between trees",
  "Lakeside cabin",
  "Elephant Butte Dam",
  "Elephant Butte State Park sign",
  "Desert landscape",
  "Tumbleweed",
  "Roadrunner",
  "Hot air balloon",
  "New Mexico flag",
  "Spicy green chile",
  "Turquoise jewelry",
  "Native American pottery",
  "Petroglyphs",
  "Sierra del Rio Golf Course",
  "Geronimo Trail Scenic Byway sign",
  "Truth or Consequences hot springs",
  "Elephant Butte Lake State Park entrance"
];